Path 2D module
TheSpyder/rescript-webapi pull request #133
Opened 2024-07-05 22:08 UTC by utenma

As result of https://github.com/TheSpyder/rescript-webapi/issues/132

Path2d module added with following js bindings, see on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Path2D#instance_methods)
- addPath
- arc()
- arcTo()
- bezierCurveTo()
- closePath()
- ellipse()
- lineTo()
- moveTo()
- quadraticCurveTo()
- rect()
- roundRect()

Syntax
```rescript
open Webapi.Canvas

let path1 = Path2d.make()
let path2 = Path2d.make(~d="M10 10 h 80 v 80 h -80 Z", ())

path1->Path2d.addPath(path2)

path1->Path2d.arc(~x=1.,~y =2.,~r=3.,~a1 = 4., ~a2 =5.,())
```

TODO
 - [ ] add Path2d module
 - [ ] export Path2d from `src/Webapi/Webapi__Canvas.res`
 - [ ] remove `Canvas2d.newPath2D()` in favor of `Path2d.make(~d=?)`
 - [ ] path2d test, check requirements with @TheSpyder
 - [ ] canvas2d test, remove path2d references
 - [ ] list breaking changes

2024-07-05 22:24 UTC, utenma commented
@TheSpyder what do you do with the generated js files from tests? are they used besides compile check?

2024-07-10 23:41 UTC, TheSpyder commented
@utenma sorry I haven't looked at this yet. The "tests" are indeed a compile check; it ensures changes made do not impact the compiled JS (unless that's intentional).

I hope to one day have full library coverage, if you could add a few extra test calls to methods you've added that would be great 👍 

Should we delete the old binding methods you're replacing?

2024-07-12 11:33 UTC, TheSpyder requested changes
Getting there! just needs a few tweaks.

2024-07-12 11:33 UTC, TheSpyder commented on src/Webapi/Canvas/Webapi__Canvas__Path_Common.res
> +module type ModuleWithT = {
The style used in this project is `Impl` and `T.t`, with the module type and module in one declaration

https://github.com/TheSpyder/rescript-webapi/blob/87270bd837a826c4ba29c7a8fe91ce7ebf04813a/src/Webapi/Dom/Webapi__Dom__Event.res#L1-L5

https://github.com/TheSpyder/rescript-webapi/blob/18d9d553201d575fa8e194d3370298b556b28747/src/Webapi/Dom/Webapi__Dom__PointerEvent.res#L4-L6

2024-07-12 11:33 UTC, TheSpyder commented on tests/Webapi/Canvas/Webapi__Canvas__Canvas2d__test.res
> +let path2 = Path2d.make(~d="M24.85,10.126c2.018-4.783,6.628-8.125,11.99-8.125c7.223"
Path2d has a new module now, might as well give it a separate test file?

2024-07-29 22:08 UTC, utenma commented
@TheSpyder updated list of breaking changes

2024-10-10 06:57 UTC, TheSpyder approved these changes
I am truly sorry for letting this sit for over 2 months. I had a long work trip and then things just kept coming up that I had to deal with first.

Just one little tweak and then I'll merge+release it.

2024-10-10 06:57 UTC, TheSpyder commented on tests/Webapi/Canvas/Webapi__Canvas__Canvas2d__test.res
> -ctx->fillPath2D(path)
These don't have an equivalent test in your new code 🤔

2024-10-10 22:29 UTC, merged

2024-10-11 00:28 UTC, TheSpyder commented on tests/Webapi/Canvas/Webapi__Canvas__Canvas2d__test.res
> -ctx->fillPath2D(path)
oh `beginPath` is already there, and the others moved. My bad.

2024-10-11 05:30 UTC, TheSpyder commented
Published as 0.10.0